spring:
  application:
    name: truck-navigation-backend
  
  datasource:
    url: jdbc:h2:mem:trucknavdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  


server:
  port: 8080

# Custom application properties
truck-navigation:
  jwt:
    secret: TruckNavigationSecretKeyForJWTTokenGeneration2024
    expiration: 86400000 # 24 hours in milliseconds
  
  routing:
    default-speed: 60 # km/h
    max-route-distance: 2000 # km
  
  maps:
    api-url: https://api.openrouteservice.org/v2
    api-key: ${MAPS_API_KEY:demo-key}

logging:
  level:
    com.trucknavigation: INFO

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

